routes/web.php
<?php

use App\Http\Controllers\MahasiswaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/', function(){
    return redirect('mahasiswa');
});
Route::resource('mahasiswa', MahasiswaController::class);

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;
    protected $table = 'mahasiswa';
    protected $guarded = [];
    public $timestamps = false;
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/MahasiswaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use Illuminate\Http\Request;

class MahasiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $mahasiswa = Student::all();
        return view('welcome', compact('mahasiswa'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => ['required'],
            'nim' => ['required', 'unique:mahasiswa,nim'],
            'jk' => ['required'],
            'prodi' => ['required'],
            'fakultas' => ['required'],
        ]);

        Student::create([
            'nama' => $request->nama,
            'nim' => $request->nim,
            'jk' => $request->jk,
            'prodi' => $request->prodi,
            'fakultas' => $request->fakultas,
        ]);

        return redirect('mahasiswa');
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $mahasiswa = Student::find($id);
        return view('detail', compact('mahasiswa'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $mahasiswa = Student::find($id);
        return view('edit', compact('mahasiswa'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => ['required'],
            'jk' => ['required'],
            'prodi' => ['required'],
            'fakultas' => ['required'],
        ]);
        $mahasiswa = Student::find($id);
        $mahasiswa->nama = $request->nama;
        $mahasiswa->jk = $request->jk;
        $mahasiswa->prodi = $request->prodi;
        $mahasiswa->fakultas = $request->fakultas;
        $mahasiswa->update();
        return redirect()->route('mahasiswa.show', $mahasiswa->id);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $mahasiswa = Student::find($id);
        $mahasiswa->delete();
        return back();
    }
}

resources/views/create.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Belajar Laravel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
    <div class="container mt-3">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <div class="card p-3">
                    <h5 class="text-center mb-3">Form Tambah Mahasiswa</h5>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('mahasiswa.store') }}" method="post">
                        @csrf
                        <input type="text" placeholder="Nama" name="nama" class="form-control" id="">
                        <input type="number" name="nim" placeholder="NIM" class="form-control mt-2" id="">
                        <select name="jk" class="form-control mt-2" id="">
                            <option value="l">Lk</option>
                            <option value="p">Pr</option>
                        </select>
                        <input type="text" name="prodi" placeholder="Prodi" class="form-control mt-2"
                            id="">
                        <input type="text" name="fakultas" placeholder="Fakultas" class="form-control mt-2"
                            id="">
                        <div class="input-group">
                            <button type="submit" class="btn btn-primary mt-3">Save</button>
                            <a href="{{ route('mahasiswa.index') }}" class="btn btn-danger mt-3 ms-2">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>

</body>

</html>

resources/views/detail.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Belajar Laravel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
    <div class="container mt-3">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="card p-3">
                    <h5 class="text-center mb-3">Detail Mahasiswa</h5>
                    <p>Nama : {{ $mahasiswa->nama }}</p>
                    <p>Nim : {{ $mahasiswa->nim }}</p>
                    <p>Jenis Kelamin : {{ $mahasiswa->jk }}</p>
                    <p>Prodi : {{ $mahasiswa->prodi }}</p>
                    <p>Fakultas : {{ $mahasiswa->fakultas }}</p>
                    <a href="{{ route('mahasiswa.edit', $mahasiswa->id) }}" class="btn btn-primary" >Edit Data</a>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>
</body>

</html>

resources/views/edit.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Belajar Laravel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
    <div class="container mt-3">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <div class="card p-3">
                    <h5 class="text-center mb-3">Form Tambah Mahasiswa</h5>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('mahasiswa.update', $mahasiswa->id) }}" method="post">
                        @csrf
                        @method('put')
                        <label for="">Nama</label>
                        <input type="text" placeholder="Nama" name="nama" value="{{ $mahasiswa->nama }}"
                        class="form-control" id="">
                        <label for="" class="mt-2">Nim</label>
                        <input type="number" disabled name="nim" class="form-control mt-2"
                        value="{{ $mahasiswa->nim }}" id="">
                        <label for="" class="mt-2">Jenis Kelamin</label>
                        <select name="jk" class="form-control mt-2" id="">
                            @if ($mahasiswa->jk == 'l')
                            <option value="l" selected>Lk</option>
                            <option value="p">Pr</option>
                            @else
                            <option value="l">Lk</option>
                            <option value="p" selected>Pr</option>
                            @endif
                        </select>
                        <label for="" class="mt-2">Prodi</label>
                        <input type="text" name="prodi" value="{{ $mahasiswa->prodi }}" placeholder="Prodi" class="form-control mt-2"
                        id="">
                        <label for="" class="mt-2">Fakultas</label>
                        <input type="text" name="fakultas"value="{{ $mahasiswa->fakultas }}" placeholder="Fakultas" class="form-control mt-2"
                            id="">
                        <div class="input-group">
                            <button type="submit" class="btn btn-primary mt-3">Save</button>
                            <a href="{{ route('mahasiswa.index') }}" class="btn btn-danger mt-3 ms-2">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>

</body>

</html>